### ISSUE TITLE
Getting error in "bazel build testdpc" command

### ISSUE THREAD

**Issue by kiritgothi** [googlesamples/android-testdpc#203] opened 2024-03-09 01:37 UTC
OS: Windows 11 and Ubuntu 22.0 tried in both, getting same error
Bazel Version : bazel 7.0.2

ERROR: /z56psvzu/external/bazel_tools/tools/android/BUILD:248:12: in runtime_deps attribute of java_binary rule @@bazel_tools//tools/android:dexer: alias '//external:android/dx_jar_import' referring to filegroup rule '@@androidsdk//:dx_jar_import' is misplaced here (expected cc_binary, cc_library, genrule, genproto, java_import, java_library, java_proto_library, java_lite_proto_library, proto_library, sh_binary or sh_library) and '@@androidsdk//:dx_jar_import' does not have mandatory providers: 'CcInfo' or 'JavaInfo'. Since this rule was created by the macro 'java_binary', the error might have been caused by the macro implementation
ERROR: /z56psvzu/external/bazel_tools/tools/android/BUILD:248:12: Analysis of target '@@bazel_tools//tools/android:dexer' failed
ERROR: Analysis of target '//:testdpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.766s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully

**Comment by kiritgothi** [comment] 2024-03-09 03:26
Getting errors while do from Android Studio Bazel Plugin As well

ERROR: /gmfixcqj/external/bazel_tools/tools/android/BUILD:14:27: While resolving toolchains for target @@bazel_tools//tools/android:android_jar (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/bazel_tools/tools/android/BUILD:248:12: in runtime_deps attribute of java_binary rule @@bazel_tools//tools/android:dexer: alias '//external:android/dx_jar_import' referring to filegroup rule '@@androidsdk//:dx_jar_import' is misplaced here (expected cc_binary, cc_library, genrule, genproto, java_import, java_library, java_proto_library, java_lite_proto_library, proto_library, sh_binary or sh_library) and '@@androidsdk//:dx_jar_import' does not have mandatory providers: 'CcInfo' or 'JavaInfo'. Since this rule was created by the macro 'java_binary', the error might have been caused by the macro implementation
ERROR: /gmfixcqj/external/bazel_tools/tools/android/BUILD:248:12: Analysis of target '@@bazel_tools//tools/android:dexer' failed
ERROR: D:/dcp-bazel/BUILD:104:16: While resolving toolchains for target //:aidl (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:68:16: While resolving toolchains for target //:test_deps (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:22:11: While resolving toolchains for target //:setupdesign_strings (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/BUILD:3:16: While resolving toolchains for target @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_stub_application (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/r8/BUILD:3:13: in deps attribute of java_library rule @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/r8:r8: alias '//external:android/d8_jar_import' referring to filegroup rule '@@androidsdk//:d8_jar_import' is misplaced here (expected cc_binary, cc_library, genrule, genproto, java_import, java_library, java_proto_library, java_lite_proto_library, proto_library, sh_binary or sh_library) and '@@androidsdk//:d8_jar_import' does not have mandatory providers: 'CcInfo' or 'JavaInfo'
ERROR: /gmfixcqj/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/r8/BUILD:3:13: Analysis of target '@@bazel_tools//src/tools/android/java/com/google/devtools/build/android/r8:r8' failed
ERROR: D:/dcp-bazel/BUILD:17:11: While resolving toolchains for target //:setupcompat (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/BUILD:11:16: While resolving toolchains for target @@bazel_tools//src/tools/android/java/com/google/devtools/build/android/incrementaldeployment:incremental_split_stub_application (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:61:16: While resolving toolchains for target //:guava_deps (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:156:11: While resolving toolchains for target @@maven//:androidx_cardview_cardview (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:31:11: While resolving toolchains for target @@maven//:androidx_annotation_annotation_experimental (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:680:11: While resolving toolchains for target @@maven//:androidx_localbroadcastmanager_localbroadcastmanager (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:914:11: While resolving toolchains for target @@maven//:androidx_versionedparcelable_versionedparcelable (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:646:11: While resolving toolchains for target @@maven//:androidx_lifecycle_lifecycle_viewmodel (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:53:16: While resolving toolchains for target //:bouncycastle_deps (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:124:11: While resolving toolchains for target @@maven//:androidx_arch_core_core_runtime (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:288:11: While resolving toolchains for target @@maven//:androidx_cursoradapter_cursoradapter (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:320:11: While resolving toolchains for target @@maven//:androidx_documentfile_documentfile (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:848:11: While resolving toolchains for target @@maven//:androidx_tracing_tracing (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:780:11: While resolving toolchains for target @@maven//:androidx_savedstate_savedstate (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:732:11: While resolving toolchains for target @@maven//:androidx_print_print (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:405:11: While resolving toolchains for target @@maven//:androidx_enterprise_enterprise_feedback (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:446:11: While resolving toolchains for target @@maven//:androidx_interpolator_interpolator (7735e62): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:405:11: While resolving toolchains for target @@maven//:androidx_enterprise_enterprise_feedback (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:31:11: While resolving toolchains for target @@maven//:androidx_annotation_annotation_experimental (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:446:11: While resolving toolchains for target @@maven//:androidx_interpolator_interpolator (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:680:11: While resolving toolchains for target @@maven//:androidx_localbroadcastmanager_localbroadcastmanager (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:22:11: While resolving toolchains for target //:setupdesign_strings (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:732:11: While resolving toolchains for target @@maven//:androidx_print_print (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:320:11: While resolving toolchains for target @@maven//:androidx_documentfile_documentfile (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:104:16: While resolving toolchains for target //:aidl (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:53:16: While resolving toolchains for target //:bouncycastle_deps (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:61:16: While resolving toolchains for target //:guava_deps (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: D:/dcp-bazel/BUILD:17:11: While resolving toolchains for target //:setupcompat (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:780:11: While resolving toolchains for target @@maven//:androidx_savedstate_savedstate (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo
ERROR: /gmfixcqj/external/maven/BUILD:646:11: While resolving toolchains for target @@maven//:androidx_lifecycle_lifecycle_viewmodel (3a4bb8f): toolchain type @@bazel_tools//tools/android:sdk_toolchain_type resolved to target @@androidsdk//:error_message, but that target does not provide ToolchainInfo

**Comment by pfmaggi** [comment] 2024-03-11 14:59
Thanks for reporting this. I see the same issue when working on a new machine that doesn't have a previous Bazel cache. It works on other machines where I usually compile this project with Bazel.

This looks like a bazel issue, and I'll monitor https://github.com/bazelbuild/bazel/issues/21612

**Comment by pfmaggi** [comment] 2024-03-13 10:36
Closing this as I cannot reproduce it with Bazel 7.1.0.

**Closed by pfmaggi** 2024-03-13 10:36 UTC
Labels: bazel
