### ISSUE TITLE
Anyone help me to create an app using testdpc

### ISSUE THREAD

**Issue by Ammypartner** [googlesamples/android-testdpc#177] opened 2023-01-17 13:52 UTC
Hi i want to create an app using testdpc

**Comment by HradeshKumar** [comment] 2023-03-19 12:53
are you able to find any solution to create Test DCP?.

**Comment by Ammypartner** [comment] 2023-03-21 21:32
No

**Comment by pfmaggi** [comment] 2023-11-23 11:31
Closing this as there not enough information to provide any guidance.

If you still have an issue with TestDPC, please open a new bug and provide detailed information of that the issue is.

**Closed by pfmaggi** 2023-11-23 11:31 UTC
