### ISSUE TITLE
disable-keyguard-features fails to register upon app update

### ISSUE THREAD

**Issue by reed-sap** [googlesamples/android-testdpc#5] opened 2016-06-01 14:00 UTC
I'd tried posting this on the Google for Work community forum, but haven't had a response in 3 weeks; I probably put the post in the wrong forum.  Original post is here: https://connect.googleforwork.com/thread/16160

As a profile owner, I would like to have the policy permissions passed to the DeviceAdminReceiver update silently in the profile as new policies are added.  We've found that these permissions are not updated when the DPC in the managed profile is.  Our specific use case shows calling setKeyguardDisabledFeatures causing an exception.  To update the permissions I have to prompt for Device Admin via ACTION_ADD_DEVICE_ADMIN _within the profile._  Is there some other method I can use to update the policies associated with the DPC without user interaction?  We haven't tried in Device Owner yet, but I suspect it'd have the same issue.

I was able to recreate this in the android-testdpc client from https://github.com/googlesamples/android-testdpc.
05-09 14:12:09.433 24303-24303/com.afwsamples.testdpc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afwsamples.testdpc, PID: 24303
    java.lang.SecurityException: Admin    
          ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.DeviceAdminReceiver} did 
          not specify uses-policy for: disable-keyguard-features
          at android.os.Parcel.readException(Parcel.java:1599)
          at android.os.Parcel.readException(Parcel.java:1552)
          at android.app.admin.IDevicePolicyManager$Stub
              $Proxy.setKeyguardDisabledFeatures(IDevicePolicyManager.java:3258)
          at android.app.admin.DevicePolicyManager.
              setKeyguardDisabledFeatures(DevicePolicyManager.java:2543)
          at com.afwsamples.testdpc.policy.keyguard.
              LockScreenPolicyFragment.updateKeyguardFeatures
              (LockScreenPolicyFragment.java:203)
          at com.afwsamples.testdpc.policy.keyguard.
              LockScreenPolicyFragment.onPreferenceChange(LockScreenPolicyFragment.java:155)
          at android.preference.Preference.callChangeListener(Preference.java:939)
          at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:65)
          at android.preference.Preference.performClick(Preference.java:994)
          at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
          at android.widget.AdapterView.performItemClick(AdapterView.java:310)
          at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
          at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
          at android.widget.AbsListView$3.run(AbsListView.java:3879)
          at android.os.Handler.handleCallback(Handler.java:739)
          at android.os.Handler.dispatchMessage(Handler.java:95)
          at android.os.Looper.loop(Looper.java:148)
          at android.app.ActivityThread.main(ActivityThread.java:5417)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Steps to Recreate:

1. Download and ensure that you're able to successfully build the android-testdpc project.
2. Edit res/xml/device_admin_receiver.xml and remove the element disable-keyguard-features
3. Compile, run and inflate the managed profile (I used a Nexus 6 running M)
4. Edit res/xml/device_admin_receiver.xml and add the element disable-keyguard-features
5. Compile and run the updated APK, ensure you open the DPC testdcp app
6. Navigate to the Lock screen restrictions preference, toggle Disable trust agents, observe an exception (and in the event of the testdpc, a crash)

(SMS-28130)
*edit, Markdown ate the xml element in the recreation steps.

**Comment by crowfeather** [comment] 2016-06-01 14:17
Thanks for the report. We're looking at this internally now. Stay tuned :)

**Comment by ming030890** [comment] 2016-06-01 19:53
I can confirm that this is a platform bug.
May I ask do you have a deployed DPC hit this issue?
If it is not the case, please request all of the device admin policies ahead of time as a workaround.
We are unlikely to add more DeviceAdmin policies in the future since we're deprecating DeviceAdmin slowly.

Thanks

**Comment by reed-sap** [comment] 2016-06-01 20:10
We do have a [deployed DPC](https://play.google.com/store/apps/details?id=com.Android.Afaria&hl=en) that will hit this issue with our next release.  We've implemented the reprompt action when we run as a Device Admin in the primary profile should the users need the additional permission, but didn't want to introduce user interaction to the managed profile.

Thanks for looking, and good to know about DeviceAdmin's future.

**Comment by ming030890** [comment] 2016-06-01 21:11
Sorry to hear about it. But I am afraid the user interaction way is the only solution now.
We have an internal bug track this issue and I am going to close this issue. Please feel free to ask if you have any other question.

Thanks

**Closed** 2016-06-01 21:11 UTC
