### ISSUE TITLE
Invalid content was found starting with element 'base-extension'

### ISSUE THREAD

**Issue by Anasmirza20** [googlesamples/android-testdpc#136] opened 2021-11-27 11:12 UTC
Hi Team

I am getting this error while building the project

cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

**Comment by jscott1989** [comment] 2021-11-29 16:26
Is anyone else seeing this issue? I've never seen it before...

**Comment by aspawa** [comment] 2022-01-01 08:36
I am getting this error while building the project

cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{codename, tag}' is expected.

**Comment by himeshshadiza** [comment] 2022-02-03 05:39
Hi @Anasmirza20 did you get any update on how to solve this issue

**Comment by KyleTrippK** [comment] 2022-02-04 11:00
Hello guys I am also facing the same error during gradle sync.

cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

**Comment by idevchandra** [comment] 2022-02-07 05:49
I am having this issue too! 

```
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)
```

**Comment by luizppa** [comment] 2022-02-07 14:36
Same issue here:

```
Android Studio: Bumblebee | 2021.1.1
macOS: 12.0
chip: apple M1
Gradle JDK: 1.8.0_32
```

**Comment by ammar-abyte** [comment] 2022-02-08 07:30
Hi, I'm getting this error while building project. Anyone here who solved that?

cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{codename, tag}' is expected.


JDK: 1.8
Android Studio Version Bumblebee 2021.1.1

**Comment by jscott1989** [comment] 2022-02-08 13:35
I'm not seeing this. We are going to be replacing the gradle build system with bazel and will update all our dependencies etc. at the same time so it should be fixed then.

I'll leave this issue open until then in case someone else figures it out

**Comment by brentscott** [comment] 2022-02-10 16:10
I was running into this same error. What fixed it for me was making sure the Gradle JDK was pointing to the right JDK (in my case JDK 1.8).  File > Project Structure > SDK Location > Gradle Settings (Link)

![gradle_settings](https://user-images.githubusercontent.com/6904303/153448200-c53c9fb6-d13b-4c00-b509-5ebf55361d75.PNG)

**Comment by exs-xgg** [comment] 2022-02-13 13:28
facing the same issue. 
i7 6700k
2021.01.01 Bumblebee

**Comment by hemantac** [comment] 2022-02-14 06:04
to fix this issue simply reset your ide settings
File - Manage IDE Settings - Restore Default Settings

**Comment by xenrobi** [comment] 2022-02-17 12:24
hey guys i have same eror here anybody already fix this error can you share in here thanks you

**Comment by uenx** [comment] 2022-02-18 03:16
I ended up fixing this by upgrading Gradle to the latest version (and modify my current source code accordingly)

**Comment by sudhin777** [comment] 2022-02-18 05:46
I am also facing the same issue. 
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

My build version was 
Android Studio Arctic Fox | 2020.3.1 Patch 4

I updated to version - Android Studio Bumblebee | 2021.1.1 Patch 1. Still issue exists. Any help is much appreciated.

**Comment by HarpreetKaur9** [comment] 2022-02-18 07:51
![Screenshot 2022-02-18 at 1 19 35 PM](https://user-images.githubusercontent.com/66735305/154640432-a32a619b-fe04-4bff-9e43-7cf9bd2a50dd.png)
Hello
Anyone have solution for this??

---------------------ISSUE----------------------

1.  cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
2.  JAVA_LETTER_OR_DIGIT

I'm facing this issue in
JDK: 1.8
Android Studio Version Bumblebee 2021.1.1

**Comment by HarpreetKaur9** [comment] 2022-02-21 07:45
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

Hello
Sudhin777

Which buildToolsVersion you used?

**Comment by HarpreetKaur9** [comment] 2022-02-21 07:51
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

Thankyou Sudhin777 
It works for me

**Comment by HarpreetKaur9** [comment] 2022-02-21 07:52
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

Facing same issue after this.

**Comment by siddhimandodi** [comment] 2022-02-23 12:54
Im also facing the same issue cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

**Comment by oliver34** [comment] 2022-02-24 09:17
does any one solved this problem? Im also facing the same issue

**Comment by gowthambalashanmugam** [comment] 2022-02-24 11:33
Any one has idea to resolve this issue ?

**Comment by zhangtao2005** [comment] 2022-02-27 02:53
I face the same problem,In my case I opened the idea.log,and it says I haven't the build-tools 28.0.3,then I installed this version of build-tools, after that, my problem solved.

**Comment by shafqat125** [comment] 2022-02-28 07:42
Add Ndk path in local.Properties like this  
ndk.dir=C\:\\Users\\UserName\\AppData\\Local\\Android\\Sdk\\ndk\\21.1.6352462

**Comment by gowthambalashanmugam** [comment] 2022-03-01 06:09
@zhangtao2005, Thank you, I had tried to play with older code but finally upgraded to latest react native and pulled all latest dependencies, hence its working fine

**Comment by arif-rahman-cse** [comment] 2022-03-08 04:42
> Add Ndk path in local.Properties like this and download ndk's from Sdk Tools in Sdk Manager ndk.dir=C:\Users\UserName\AppData\Local\Android\Sdk\ndk\21.1.6352462 ![shot_one](https://user-images.githubusercontent.com/98800883/155959663-2e18a813-1381-4844-b1d7-c8e7a285ac5b.png) ![shot_two](https://user-images.githubusercontent.com/98800883/155959669-3f06d6fb-01d1-4703-bf41-3b9c32b959f1.png)

Thank you

**Comment by bdmostafa** [comment] 2022-03-09 14:12
I have the issues related to base-extension. I used `distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip` in  `gradle-wrapper.properties` file and `classpath 'com.android.tools.build:gradle:2.2.3'` in `build.gradle` file of android directory.
![image](https://user-images.githubusercontent.com/62140337/157458049-da8a92ab-d254-4169-a325-0984452905d3.png)
This error returns when `npx react-native run-android` is run

![image](https://user-images.githubusercontent.com/62140337/157457381-22e5fa6c-a1ef-4660-a4de-974c07735e05.png)
Also, I tried to open project on Android Studio. This is the error of it.

**Comment by sbr5136014** [comment] 2022-03-09 14:43
> Hi Team
> 
> I am getting this error while building the project
> 
> cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.

Same issue

**Comment by thienthancuagio** [comment] 2022-03-10 14:18
i fixed it. Please check the configuration below
![image](https://user-images.githubusercontent.com/32169036/157680289-7bc62af7-8b04-4c63-a674-c3193d083bf0.png)

**Comment by zhouyingge1104** [comment] 2022-03-13 08:17
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

This works for me, thanks a lot!

**Comment by Languomao** [comment] 2022-03-16 08:24
It is possible that your SDK tools version is too new. Check the version through “adb version“ and reinstall the corresponding old version according to your needs，after that, my problem solved.
![image](https://user-images.githubusercontent.com/30653241/158547300-03cfc6d4-0ffd-4068-a70f-22b43616d520.png)

**Comment by beyrakIn** [comment] 2022-03-20 23:19
Thanks for the help.

**Comment by thehunzter** [comment] 2022-03-29 14:52
You should to check Gradle version and pluggin (class part gradle) version. And change with fit
https://developer.android.com/studio/releases/gradle-plugin

**Comment by avinashgoswami** [comment] 2022-04-07 10:57
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

Worked for me, Thanks

**Comment by kckunal2612** [comment] 2022-04-08 00:08
I am also facing this issue but sadly none of the suggestions made above work for me.

Here's the 2 error messages I see -
`cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.`
`cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{codename, tag}' is expected.`

I think this _could_ be an M1 Chip issue as this didn't happen to me on an Intel chip.
Any help would be appreciated.

**Comment by voonngee** [comment] 2022-04-10 13:33
Same here.

3 error messages:- 
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
cvc-complex-type.2.4.d: Invalid content was found starting with element 'base-extension'. No child element is expected at this point.
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{codename, tag}' is expected.

Android Studio Bumblebee | 2021.1.1 Patch 1
M1 Chip

**Comment by GhiathAlbawab0** [comment] 2022-04-11 14:12
any updates?

**Comment by kckunal2612** [comment] 2022-04-13 21:06
> I am also facing this issue but sadly none of the suggestions made above work for me.
> 
> Here's the 2 error messages I see - `cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.` `cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{codename, tag}' is expected.`
> 
> I think this _could_ be an M1 Chip issue as this didn't happen to me on an Intel chip. Any help would be appreciated.

So here's an update - I was finally able to fix this issue on my M1 Pro machine. ✅ 

_The fix -_

- Updated `gradle-wrapper.properties` to use gradle version 6.9.0.
- Updated my build.gradle to use architecture components version 2.4.0 (look for `kapt "androidx.room:room-compiler..."`).

_Now why did these changes work for me?_
1. Gradle 6.9 was the first release to include Apple Silicon Support. (see [release notes](https://docs.gradle.org/6.9/release-notes.html)). Thus, upgrading to this version was the first step (as has also been suggested by Google [here](https://androidstudio.googleblog.com/2021/04/android-studio-arctic-fox-canary-15.html)).

![Screenshot 2022-04-13 at 5 04 51 PM](https://user-images.githubusercontent.com/4411464/163270137-96f86bd2-7f82-436e-9932-541ae84fa26e.png)

2. Instead of building from Android studio, I ran the gradlew build command. Once done, I looked at the error logs, and noticed an error for SQLite Room DB. 
`Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64 at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333) at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) at androidx.room.verifier.DatabaseVerifier.(DatabaseVerifier.kt:71) ...`
I looked up online and [this StackOverflow answer](https://stackoverflow.com/a/68922955/4768284) seemed to give the _solution that worked for me.
Explanation_ - Room DB, part of Android architecture components library, uses SQLite internally, which had compatibility issues with the new Apple Silicon architecture. This was fixed in one of the Room alphas and updated in the [Release Notes](https://developer.android.com/jetpack/androidx/releases/room#2.4.0-alpha03). 

I hope you find this fix useful.

**Comment by sachingurnaney** [comment] 2022-04-24 19:38
> I'm not seeing this. We are going to be replacing the gradle build system with bazel and will update all our dependencies etc. at the same time so it should be fixed then.
> 
> I'll leave this issue open until then in case someone else figures it out

Update gradle version and target JDK 11 fixed my issue.

**Comment by JasonGaoH** [comment] 2022-04-25 11:41
> Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
> 
> Finally i was able to fix this issue, by updating **Android Gradle Plugin Version** and **Gradle Version**.
> 
> **Android Studio Configuration:** Android Studio Bumblebee | 2021.1.1 Patch 1 JDK: 1.8
> 
> ![image](https://user-images.githubusercontent.com/3404748/154654064-7a5700e2-d2dd-451e-af84-d77e5e80730f.png)

This worked for me，Thanks。

**Comment by jscott1989** [comment] 2022-05-10 10:24
Closing all outstanding pull requests + issues as we've reworked the app to now build with Bazel. With this change, we should be able to properly accept pull requests going forward so these won't sit around for so long. If this is still relevant please check it with the latest version [Using the Android T SDK] and re-open.

**Closed by jscott1989** 2022-05-10 10:24 UTC

**Comment by DanteAndroid** [comment] 2022-05-24 01:13
> to fix this issue simply reset your ide settings File - Manage IDE Settings - Restore Default Settings

Works like magic

**Comment by hamzaabualkhair** [comment] 2022-06-14 14:31
Hello all, I also faced similar issue. cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
Finally i was able to fix this issue, by Go To File>>Settings>>Build, Execution, Deployment>Build Tools
And I am enable "Reload project after changes in the build scripts">Any changes
after this Appeared  new Error "Add Google maven repository" 
I add Google maven repository to build.gradle and project worked without any errors
![لقطة الشاشة 2022-06-14 162058](https://user-images.githubusercontent.com/73816264/173600858-2a7bfa25-882b-4262-becb-95d92194083b.png)

**Comment by sundy19** [comment] 2022-06-17 22:32
this is work for me also. thanks
![image](https://user-images.githubusercontent.com/57116184/174408958-18869783-6ac2-4c96-83b5-6c7b685b9594.png)

**Comment by JauneQ** [comment] 2022-08-12 03:10
my project' s compileSdkVersion and targetSdkVersion is API 28, so i remove the latest SDK Platforms and Android SDK Build-Tools, it works for me
![image](https://user-images.githubusercontent.com/50310513/184277830-cf565599-34e6-4edc-9956-f0f3c97c038b.png)
![image](https://user-images.githubusercontent.com/50310513/184277886-1541c024-ba50-4d83-8319-49223489a6eb.png)

**Comment by afridi315** [comment] 2022-08-23 14:43
As per my experience, most of the time it happens when your gradle version and gradle distributionUrl are not matching. Make sure you are using the right gradle version for you project. the following link may help, [Gradle Versioning] (https://developer.android.com/studio/releases/gradle-plugin#updating-gradle)

**Comment by top-comengineer** [comment] 2023-05-07 07:54
Hello dear community.
I am building react-native project for android.
But, unfortunately, I face the same errors like the above.
Already set Android gradle plugin and gradle version according to the best solutions.
But, the same error is occured in my side.
Help me.
